### ISSUE TITLE
Cannot write logfile

### ISSUE THREAD

**Issue by wlugmayr** [bionanopatterning/Ais#1]
I installed Ais for a different user and when the software had a problem the following error message appears:

Traceback (most recent call last):
  File "/gpfs/cssb/software/rhel9/anaconda3/envs/ais-2024.3/bin/ais-cryoet", line 8, in <module>
    sys.exit(main())
  File "/gpfs/cssb/software/rhel9/anaconda3/envs/ais-2024.3/lib/python3.9/site-packages/Ais/main.py", line 43, in main
    segmentation_editor.on_update()
  File "/gpfs/cssb/software/rhel9/anaconda3/envs/ais-2024.3/lib/python3.9/site-packages/Ais/core/segmentation_editor.py", line 276, in on_update
    self.gui_main()
  File "/gpfs/cssb/software/rhel9/anaconda3/envs/ais-2024.3/lib/python3.9/site-packages/Ais/core/segmentation_editor.py", line 1816, in gui_main
    self._warning_window()
  File "/gpfs/cssb/software/rhel9/anaconda3/envs/ais-2024.3/lib/python3.9/site-packages/Ais/core/segmentation_editor.py", line 1858, in _warning_window
    cfg.write_to_log(cfg.error_msg)
  File "/gpfs/cssb/software/rhel9/anaconda3/envs/ais-2024.3/lib/python3.9/site-packages/Ais/core/config.py", line 78, in write_to_log
    with open(log_path, "a") as f:
PermissionError: [Errno 13] Permission denied: '/gpfs/cssb/software/rhel9/anaconda3/envs/ais-2024.3/lib/python3.9/site-packages/Ais/Ais.log’

I think the logfile location should be the actual directory of the user, or?

**Comment by bionanopatterning** [comment]
You are right, thanks for letting me know. 
Verion 1.0.27 is now available on pip, and it saves settings and logfiles in ~/.Ais 

I'll look in to your other issue next 👍
